ARG REGISTRY=registry.fedoraproject.org
ARG DEFAULT_IMAGE=fedora-minimal
ARG DEFAULT_TAG=41

FROM ${REGISTRY}/${DEFAULT_IMAGE}:${DEFAULT_TAG}

RUN dnf install -y \
    rpm-build \
    rpm-devel \
    rpmlint \
    diffutils \
    patch \
    rpmdevtools \
    rpkg \
    mock \
    git \
    git-lfs \
    sudo

RUN dnf clean all -y
RUN dnf autoremove -y
RUN rm -fr /var/cache/dnf/*

# Add a non-root user to the container
# This creates better reproducibility as `mock`does not run as root
# in COPR.

ARG USERNAME="mocker"
ARG USER_ID=1000
ARG USER_GID=$USER_ID
ARG GROUP_MOCK="mock"

RUN groupadd --gid ${USER_GID} ${USERNAME}

RUN useradd -m ${USERNAME} --uid ${USER_ID} --gid ${USER_GID} -G ${GROUP_MOCK}

# Add sudo capabilities just in case
RUN echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# We'll leave the default user as root
# Users can switch the user in the devcontainer with the `remoteUser` option.

#USER ${USERNAME}