name: Validate Renovate

on:
  pull_request:
    paths:
      - "**/renovate.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict