# This workflow is adapted from https://github.com/ublue-os/packages/blob/main/.github/workflows/build-package.yml

name: Test Changes

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - '.devcontainer/**'
            - '.github/**'
            - 'README.md'
            - '.gitignore'
            - 'CONTRIBUTING.md'
            - 'Justfile'

jobs:
    changed_specs:
        runs-on: ubuntu-24.04
        outputs:
            changed-specs: ${{ steps.changed-files.outputs.changed-specs }}
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

            - name: Get changed files
              id: changed-files
              run: |
                files_list="$(git diff --name-only origin/main HEAD | xargs)"
                CHANGED_SPECS="{\"specs\":[]}"
                for file in ${files_list}; do
                    if [[ ${file##*.} == "spec" ]]; then
                        spec_path=$(realpath ${file})
                        CHANGED_SPECS=$(echo ${CHANGED_SPECS} | jq -c ".specs += [\"${spec_path}\"]")
                    fi
                done

                echo "changed-specs=$(echo ${CHANGED_SPECS} | jq -c '.specs')" >> ${GITHUB_OUTPUT}
    
    build_packages:
        runs-on: ubuntu-24.04
        needs: changed_specs
        if: ${{ needs.changed_specs.outputs.changed-specs != '[]' }}
        strategy:
            fail-fast: false
            matrix:
                specs: ${{ fromJson(needs.changed_specs.outputs.changed-specs) }}
        steps:
            -  name: Checkout
               uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

            - name: Setup Just
              uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff

            - name: Build ${{ matrix.specs }}
              id: build-packages
              run: |
                just=$(which just)

                ${just} ci ${{ matrix.specs }} --enable-network
    
    check:
        runs-on: ubuntu-24.04
        if: always()
        needs: build_packages
        steps:
            - name: Check
              env:
                JOBS: ${{ toJSON(needs) }}
              run: |
                for job in $(echo ${JOBS} | jq -r 'to_entries[] | .value.result'); do
                    if [ "$job" != "success" ] && [ "$job" != "skipped" ]; then
                        exit 1
                    fi
                done
